# torch_learning

## 텐서 사용하기


In [2]:
import torch

print(torch.tensor([1, 2, 3]))
print(torch.Tensor([[1, 2, 3], [4, 5, 6]]))
print(torch.LongTensor([1, 2, 3]))
print(torch.FloatTensor([1, 2, 3]))

tensor([1, 2, 3])
tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor([1, 2, 3])
tensor([1., 2., 3.])


## 텐서 속성

In [3]:
import torch

tensor = torch.rand(1, 2)

print(tensor)
print(tensor.shape)
print(tensor.dtype)
print(tensor.device)

tensor([[0.8338, 0.5583]])
torch.Size([1, 2])
torch.float32
cpu


## 텐서 차원 변환

In [5]:
import torch

tensor = torch.rand(1, 2)
print(tensor)

tensor = tensor.reshape(2, 1)
print(tensor)

tensor([[0.7230, 0.3974]])
tensor([[0.7230],
        [0.3974]])


## 자료형 설정

In [7]:
import torch

print(torch.rand((3, 3), dtype=torch.float))

tensor([[0.5739, 0.5075, 0.5003],
        [0.2090, 0.3264, 0.1775],
        [0.1458, 0.5820, 0.0034]])


## 장치 설정

In [10]:
import torch

device = 'cuda' if torch.cuda.is_available() else 'cpu'
cpu = torch.FloatTensor([1, 2, 3])
gpu = torch.cuda.FloatTensor([1, 2, 3])
tensor = torch.rand((1, 1), device=device)

print(device)
print(cpu)
print(gpu)
print(tensor)


cuda
tensor([1., 2., 3.])
tensor([1., 2., 3.], device='cuda:0')
tensor([[0.0292]], device='cuda:0')


## 장치 변환

In [11]:
import torch

cpu = torch.FloatTensor([1, 2, 3])
gpu = cpu.cuda()
gpu2cpu = gpu.cpu()

print(cpu)
print(gpu)
print(gpu2cpu)


tensor([1., 2., 3.])
tensor([1., 2., 3.], device='cuda:0')
tensor([1., 2., 3.])


## NumPy 변환 

In [14]:
import torch
import numpy as np

print(torch.tensor(np.array([1, 2, 3], dtype = np.uint8)))
print(torch.Tensor(np.array([1, 2, 3], dtype = np.uint8)))
print(torch.from_numpy(np.array([1, 2, 3], dtype = np.uint8)))

tensor([1, 2, 3], dtype=torch.uint8)
tensor([1., 2., 3.])
tensor([1, 2, 3], dtype=torch.uint8)


## Tensor 변환 

In [15]:
import torch

tensor = torch.cuda.FloatTensor([1, 2, 3])
ndarray = tensor.detach().cpu().numpy()

print(ndarray)

[1. 2. 3.]
