In [2]:
# bool

hungry = True
sleepy = False
type(hungry)
not hungry
hungry and sleepy
hungry or sleepy

True

In [5]:
#class

class Man:
    def __init__(self, name):
        self.name = name
        print("Initialized!")
        
    def hello(self):
        print("Hello " + self.name + "!")
        
    def goodbye(self):
        print("Good-bye " + self.name + "!")
        
m = Man("David")
m.hello()
m.goodbye()

Initialized!
Hello David!
Good-bye David!


In [8]:
#numpy
import numpy as np

x = np.array([1.0, 2.0, 3.0])
print(x)
type(x)




[1. 2. 3.]


numpy.ndarray

In [9]:
x = np.array([1.0, 2.0, 3.0])
y = np.array([2.0, 4.0, 3.0])
print(x + y)
print(x -y)
print(x * y)
print(x / y)

[3. 6. 6.]
[-1. -2.  0.]
[2. 8. 9.]
[0.5 0.5 1. ]


In [10]:
x = np.array([1.0, 2.0, 3.0])
x / 2.0


array([0.5, 1. , 1.5])

In [17]:
A = np.array([[1, 2], [3, 4]])
print(A)
A.dtype
A.shape


[[1 2]
 [3 4]]


(2, 2)

In [18]:
B = np.array([[3,0], [0, 6]])
A + B

array([[ 4,  2],
       [ 3, 10]])

In [19]:
A*B

array([[ 3,  0],
       [ 0, 24]])

In [20]:
print(A)
A*10

[[1 2]
 [3 4]]


array([[10, 20],
       [30, 40]])